workflows:
  build-android:
    name: Cordova Android Build
    environment:
      node: 16.20.0 # Updated from 12 to 16
      vars:
        CORDOVA_ANDROID_VERSION: 9.1.0
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
      - name: Prepare Cordova project
        script: |
          cordova platform add android@$CORDOVA_ANDROID_VERSION
          cordova plugin add https://github.com/dagatsoin/cordova-plugin-mapbox.git --nofetch
          cordova build android
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - lokluis@gmail.com
